### ISSUE TITLE
No checkpoint saved for TM training

### ISSUE THREAD

**Issue by kamanphoebe** [cbaziotis/lm-prior-for-nmt#8]
Hi,

I am trying to train a TM using the following command:
`python nmt_prior.py --config ../configs/transformer/trans.deen_base.yaml --name final.trans.deen_base`
The training was good until the end of the last epoch, an error appeared:

> Traceback (most recent call last):
  File "/home/ubuntu-user/mc35180/lm-prior-for-nmt/models/nmt_prior.py", line 143, in <module>
    eval_best(trained_model)
  File "/home/ubuntu-user/mc35180/lm-prior-for-nmt/models/../models/nmt_prior_helpers.py", line 121, in eval_best
    eval_nmt_checkpoint(trainer.best_checkpoint,
  File "/home/ubuntu-user/mc35180/lm-prior-for-nmt/models/../models/translate.py", line 110, in eval_nmt_checkpoint
    _base, _file = os.path.split(checkpoint)
  File "/home/ubuntu-user/anaconda3/envs/lmprior/lib/python3.9/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

And there is no any checkpoints ever saved in the experiment directory. How can I fix this?

**Comment by kamanphoebe** [comment]
I added a CheckpointCallback in line 99 of `nmt_prior.py` and there is a saved checkpoint now:
```python
  callbacks = [
      LossCallback(config["logging"]["log_interval"]),
      GradientCallback(config["logging"]["log_interval"]),
      ModuleGradientCallback(["encoder"], config["logging"]["log_interval"]),
      SamplesCallback(config["logging"]["log_interval"]),
      EvalCallback(config["logging"]["eval_interval"], keep_best=True,
                   early_stop=config["optim"]["early_stop"]),
      CheckpointCallback(config["logging"]["checkpoint_interval"], # line 99
          only_best=True,
          early_stop=config["optim"].get("early_stop", 100)),
  ]
```
Is this correct?

**Comment by kamanphoebe** [comment]
After the modification, a new error shows up during translating: 
`"index_select_out_cuda_impl" not implemented for 'Float'`.
